# Generated by Django 5.1.4 on 2024-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído'), ('F', 'Falha')], default='P', max_length=1)),
            ],
            options={
                'verbose_name': 'Conversão',
                'verbose_name_plural': 'Conversões',
            },
        ),
    ]
