# Generated by Django 5.1.4 on 2024-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversao',
            options={},
        ),
        migrations.RemoveField(
            model_name='conversao',
            name='status',
        ),
        migrations.AlterField(
            model_name='conversao',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
